#!/bin/bash
set -e

source .env
export ROLLBAR_TOKEN
export ROLLBAR_ENVIRONMENT

cd /opt/star-burger
source /opt/star-burger/env/bin/activate
git pull origin main
pip install -r requirements.txt

npm ci
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

python manage.py collectstatic --noinput
python manage.py migrate --run-syncdb

systemctl restart star-burger.service
systemctl reload nginx.service

commit=`git rev-parse HEAD`
curl -H "X-Rollbar-Access-Token: $ROLLBAR_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d "{\"environment\": \"$ROLLBAR_ENVIRONMENT\", \"revision\": \"$commit\", \"status\": \"succeeded\"}"

echo "!!!Deployment complete!!!"
