#!/bin/bash
set -e

source .env

echo "ROLLBAR_TOKEN: $ROLLBAR_TOKEN"
echo "ROLLBAR_ENVIRONMENT: $ROLLBAR_ENVIRONMENT"

cd /opt/star-burger

source /opt/star-burger/env/bin/activate

git pull origin main

pip install -r requirements.txt

npm ci --dev

./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

python manage.py collectstatic --noinput

python manage.py migrate --run-syncdb

systemctl restart star-burger.service

systemctl reload nginx.service

echo "!!!Deployment complete!!!"


commit = $(git rev-parse HEAD)

curl -H "X-Rollbar-Access-Token: $ROLLBAR_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d '{"environment": "$ROLLBAR_ENVIRONMENT", "revision": "$commit", "status": "succeeded"}'
