#!/bin/bash
set -e

PROJECT_DIR="/opt/star-burger"

echo "===> Start deployment"

cd "$PROJECT_DIR"

git pull origin main

docker compose up -d --build

echo "===> Deployment completed successfully" -d --build



