#!/bin/bash
set -e

PROJECT_DIR="/opt/star-burger"

echo "===> Start deployment"

cd "$PROJECT_DIR"

git pull origin main

docker compose up -d --build

docker compose exec django python manage.py migrate

docker compose exec django python manage.py collectstatic --noinput

docker compose restart nginx

echo "===> Deployment completed successfully" -d --build



