#!/usr/bin/env bash

set -e

SOURCE_DIR="/opt/star-burger/media"
MEDIA_VOLUME="star-burger_media"

echo "===> Copy media files to Docker volume"
docker pull alpine
docker run --rm \
  -v ${MEDIA_VOLUME}:/data \
  -v ${SOURCE_DIR}:/source \
  alpine sh -c "
        cp -r /source/* /data/ &&
        chmod -R a+rX /data
  "

echo "===> Media files loaded into volume successfully"

echo "===> Remove temporary source directory"
rm -rf "$SOURCE_DIR"

echo "===> Done"
