# Generated by Django 3.2.15 on 2025-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250118_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('raw', 'Необработанный'), ('assembled', 'Cборка'), ('delivery', 'Доставка'), ('ready', 'Готов')], db_index=True, default='raw', max_length=20, verbose_name='Статус'),
        ),
    ]
