# Generated by Django 3.2.15 on 2025-01-18 20:59

from django.db import migrations


def update_price(apps, schema_editor):
    OrderDetails = apps.get_model('foodcartapp', 'OrderDetails')
    for detail in OrderDetails.objects.all():
        detail.price = detail.product.price
        detail.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderdetails_price'),
    ]

    operations = [
        migrations.RunPython(update_price),
    ]
